language: scala

scala:
- 2.11.12
- 2.12.6

env:
- SCALAENV=jvm
- SCALAENV=js
- SCALAENV=all
- FREESBUILD=docs

matrix:
  exclude:
  - scala: 2.11.12
    env: FREESBUILD=docs
  - env: SCALAENV=all

jdk:
- oraclejdk8

before_cache:
- du -h -d 1 $HOME/.ivy2/
- du -h -d 2 $HOME/.sbt/
- du -h -d 4 $HOME/.coursier/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
- find $HOME/.coursier/cache -name "*.lock" -type f -delete

cache:
  directories:
  - $HOME/.sbt/1.0
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/cache
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.coursier

before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    openssl aes-256-cbc -K $encrypted_86276aecec54_key -iv $encrypted_86276aecec54_iv -in secring.gpg.enc -out secring.gpg -d;
  fi
- export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.6.0 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

script:
- if [ "$SCALAENV" = "jvm" ]; then
    sbt ++$TRAVIS_SCALA_VERSION validateJVM;
  elif [ "$SCALAENV" = "js" ]; then
    sbt ++$TRAVIS_SCALA_VERSION validateJS;
  elif [ "$FREESBUILD" = "docs" ]; then
    sbt ++$TRAVIS_SCALA_VERSION docs/tut;
  else
    echo "You might not be invited to the party";
  fi

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
    - 'https://webhook.atomist.com/atomist/travis/teams/T024G6JTP'
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always

jobs:
  include:
    - stage: deploy
      script:
        - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
            if grep -q "SNAPSHOT" version.sbt; then
              sbt +publish;
            else
              if [ "$SCALAENV" = "all" ]; then
                sbt orgUpdateDocFiles;
                git reset --hard HEAD;
                git clean -f;
                git checkout master;
                git pull origin master;
                sbt release;
                git clone https://github.com/frees-io/freestyle-rpc.git;
                cd freestyle-rpc && sbt docs/tut && cd ..;
                git clone https://github.com/frees-io/freestyle-cassandra.git;
                cd freestyle-cassandra && sbt docs/tut && cd ..;
                sbt docs/publishMicrosite;
              fi
            fi
          fi
      scala: 2.12.4
      env: SCALAENV=all
